// WordPress integration: named-error classification + insertion semantics.
//
// We cannot easily stand up real Wordfence/iThemes locally, so we drive
// pushLink with response stubs that match the wire-level signatures recto
// will see in the wild. This ensures every failure path PRD §FR-PUSH-04
// promises a named code for actually receives one.

import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { insertLink, pushLink, type PushInput } from '../src/integrations/wordpress';

// 32-byte zero key → predictable AES for the encrypted-secret round-trip.
const KEK = 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=';

async function makeEncrypted(plain: string): Promise<Uint8Array> {
  const { encrypt } = await import('../src/lib/crypto');
  return encrypt(plain, KEK);
}

function baseInput(overrides: Partial<PushInput> = {}): PushInput {
  return {
    siteUrl: 'https://example.com',
    username: 'admin',
    encryptedSecret: new Uint8Array([1, 2, 3, 4]), // valid bytes; will be replaced per test
    postId: 42,
    anchorText: 'related thinking',
    targetHref: 'https://example.com/orphan',
    paragraphMarker: 'the marker text',
    ...overrides,
  };
}

describe('insertLink — wrap an existing phrase (new signature)', () => {
  // insertLink(original, anchorPhrase, href, scopeHint?)
  it('wraps the existing phrase in place', () => {
    const out = insertLink(
      '<p>before the marker text and the rest</p>',
      'marker text',
      'https://example.com/orphan'
    );
    expect(out.alreadyLinked).toBe(false);
    expect(out.via).toBe('wrap');
    expect(out.content).toContain('data-recto-link="1"');
    expect(out.content).toContain('>marker text</a>');
  });

  it('flags phraseNotFound and leaves the body untouched when the phrase is absent', () => {
    const body = '<p>this body has no such phrase</p>\n\n<p>next paragraph</p>';
    const out = insertLink(body, 'absent string here', 'https://example.com/target');
    expect(out.phraseNotFound).toBe(true);
    expect(out.content).toBe(body);
  });

  it('refuses duplicate insertion when an identical href is already in the body', () => {
    const out = insertLink(
      '<p>already <a href="https://example.com/orphan">linked</a></p>',
      'already',
      'https://example.com/orphan'
    );
    expect(out.alreadyLinked).toBe(true);
  });

  it('allows a DIFFERENT-target link in a post that already holds a recto marker (hub → many orphans)', () => {
    // Previously the bare data-recto-link marker short-circuited ANY second
    // insertion; a hub post could link exactly one orphan. Idempotency is keyed
    // on the specific target href, so a new target must be inserted.
    const out = insertLink(
      '<p>earlier <a data-recto-link="1" href="https://example.com/other">link</a></p>',
      'earlier',
      'https://example.com/target'
    );
    expect(out.alreadyLinked).toBe(false);
    expect(out.phraseNotFound).toBeFalsy();
    expect(out.content).toContain('href="https://example.com/target"');
    expect(out.content).toContain('href="https://example.com/other"');
  });
});

describe('pushLink — failure-code classification', () => {
  beforeEach(() => {
    vi.useFakeTimers();
    vi.setSystemTime(new Date('2026-05-29T11:00:00Z'));
  });
  afterEach(() => {
    vi.useRealTimers();
    vi.restoreAllMocks();
  });

  async function withFetch(stub: (url: string, init?: RequestInit) => Response | Promise<Response>) {
    vi.stubGlobal('fetch', vi.fn(async (url: string, init?: RequestInit) => stub(url, init)) as any);
    return makeEncrypted('VFcye71lskZfg524pevNyYSd');
  }

  it('wp_auth_failed on 401', async () => {
    const secret = await withFetch(() => new Response('Unauthorized', { status: 401 }));
    const r = await pushLink({ RECTO_KEK: KEK }, baseInput({ encryptedSecret: secret }));
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.code).toBe('wp_auth_failed');
  });

  it('wp_security_blocked on 403 (Wordfence-shaped)', async () => {
    const secret = await withFetch(() => new Response('<html>Generated by Wordfence</html>', { status: 403 }));
    const r = await pushLink({ RECTO_KEK: KEK }, baseInput({ encryptedSecret: secret }));
    if (r.ok) throw new Error('should have failed');
    expect(r.code).toBe('wp_security_blocked');
  });

  it('wp_post_not_found on 404', async () => {
    const secret = await withFetch(() => new Response('Not Found', { status: 404 }));
    const r = await pushLink({ RECTO_KEK: KEK }, baseInput({ encryptedSecret: secret }));
    if (r.ok) throw new Error('should have failed');
    expect(r.code).toBe('wp_post_not_found');
  });

  it('wp_rest_disabled on 406 (some hardening plugins)', async () => {
    const secret = await withFetch(() => new Response('Not Acceptable', { status: 406 }));
    const r = await pushLink({ RECTO_KEK: KEK }, baseInput({ encryptedSecret: secret }));
    if (r.ok) throw new Error('should have failed');
    expect(r.code).toBe('wp_rest_disabled');
  });

  it('wp_network when fetch throws', async () => {
    vi.stubGlobal('fetch', vi.fn(async () => { throw new TypeError('refused'); }) as any);
    const secret = await makeEncrypted('VFcye71lskZfg524pevNyYSd');
    const r = await pushLink({ RECTO_KEK: KEK }, baseInput({ encryptedSecret: secret }));
    if (r.ok) throw new Error('should have failed');
    expect(r.code).toBe('wp_network');
  });

  it('wp_already_linked only when THIS orphan href is already present (per-href idempotency)', () => {
    // The post already links the SAME target (/orphan) → genuine duplicate.
    const existing = '<p>related thinking is <a data-recto-link="1" href="https://example.com/orphan">here</a></p>';
    return withFetch((u, init) => {
      if ((init?.method ?? 'GET') === 'GET') {
        return new Response(JSON.stringify({ id: 42, content: { raw: existing } }), {
          status: 200,
          headers: { 'content-type': 'application/json' },
        });
      }
      return new Response('', { status: 200 });
    }).then(async (secret) => {
      const r = await pushLink({ RECTO_KEK: KEK }, baseInput({ encryptedSecret: secret }));
      if (r.ok) throw new Error('should have failed');
      expect(r.code).toBe('wp_already_linked');
    });
  });

  it('does NOT report already_linked when only a DIFFERENT orphan is linked in the post', async () => {
    // /other is linked; we push /orphan, whose phrase IS present → it wraps and
    // POSTs (a hub linking a second orphan). Proves the broad-marker bug is gone.
    const existing = '<p>related thinking lives here, and <a data-recto-link="1" href="https://example.com/other">other</a> too.</p>';
    let posted = false;
    const secret = await withFetch((u, init) => {
      if ((init?.method ?? 'GET') === 'GET') {
        return new Response(JSON.stringify({ id: 42, content: { raw: existing } }), {
          status: 200, headers: { 'content-type': 'application/json' },
        });
      }
      posted = true;
      return new Response(JSON.stringify({ id: 42 }), { status: 200, headers: { 'content-type': 'application/json' } });
    });
    const r = await pushLink({ RECTO_KEK: KEK }, baseInput({ encryptedSecret: secret }));
    expect(r.ok).toBe(true);
    expect(posted).toBe(true);
  });

  it('happy path → ok with revisionId', async () => {
    const existing = '<p>first paragraph here.</p>\n\n<p>second paragraph.</p>';
    let calls = 0;
    const secret = await withFetch((u, init) => {
      calls += 1;
      if (calls === 1) {
        return new Response(JSON.stringify({ id: 42, content: { raw: existing } }), {
          status: 200,
          headers: { 'content-type': 'application/json' },
        });
      }
      return new Response(JSON.stringify({ id: 42, modified: '2026-05-29T11:00:01' }), {
        status: 200,
        headers: { 'content-type': 'application/json' },
      });
    });
    const r = await pushLink(
      { RECTO_KEK: KEK },
      baseInput({ encryptedSecret: secret, anchorText: 'first paragraph', paragraphMarker: 'first paragraph here.' })
    );
    expect(r.ok).toBe(true);
    if (r.ok) expect(r.postId).toBe(42);
  });
});
