// WordPress integration: named-error classification + insertion semantics.
//
// We cannot easily stand up real Wordfence/iThemes locally, so we drive
// pushLink with response stubs that match the wire-level signatures recto
// will see in the wild. This ensures every failure path PRD §FR-PUSH-04
// promises a named code for actually receives one.

import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { insertLink, pushLink, type PushInput } from '../src/integrations/wordpress';

// 32-byte zero key → predictable AES for the encrypted-secret round-trip.
const KEK = 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=';

async function makeEncrypted(plain: string): Promise<Uint8Array> {
  const { encrypt } = await import('../src/lib/crypto');
  return encrypt(plain, KEK);
}

function baseInput(overrides: Partial<PushInput> = {}): PushInput {
  return {
    siteUrl: 'https://example.com',
    username: 'admin',
    encryptedSecret: new Uint8Array([1, 2, 3, 4]), // valid bytes; will be replaced per test
    postId: 42,
    anchorText: 'related thinking',
    targetHref: 'https://example.com/orphan',
    paragraphMarker: 'the marker text',
    ...overrides,
  };
}

describe('insertLink', () => {
  it('inserts after the verbatim marker when present', () => {
    const out = insertLink(
      '<p>before the marker text and the rest</p>',
      'the marker text',
      'related thinking',
      'https://example.com/orphan'
    );
    expect(out.alreadyLinked).toBe(false);
    expect(out.via).toBe('marker');
    expect(out.content).toContain('data-recto-link="1"');
    expect(out.content).toContain('>related thinking</a>');
  });

  it('falls back to first-paragraph when marker is missing', () => {
    const out = insertLink(
      '<p>this body has no marker</p>\n\n<p>next paragraph</p>',
      'absent string',
      'anchor',
      'https://example.com/target'
    );
    expect(out.markerMissing).toBeUndefined();
    expect(out.via).toBe('first-paragraph');
    expect(out.content).toContain('data-recto-link="1"');
    // The injected paragraph appears between the two existing paragraphs.
    const split = out.content.split('data-recto-link="1"');
    expect(split.length).toBe(2);
  });

  it('flags markerMissing when there is no paragraph break at all', () => {
    const out = insertLink(
      'flat-string-no-paragraphs-at-all',
      'absent',
      'anchor',
      'https://example.com/target'
    );
    expect(out.markerMissing).toBe(true);
    expect(out.content).toBe('flat-string-no-paragraphs-at-all');
  });

  it('refuses duplicate insertion when an identical href is already in the body', () => {
    const out = insertLink(
      '<p>already <a href="https://example.com/orphan">linked</a></p>',
      'whatever',
      'anchor',
      'https://example.com/orphan'
    );
    expect(out.alreadyLinked).toBe(true);
  });

  it('refuses duplicate insertion when a previous recto marker is present', () => {
    const out = insertLink(
      '<p>earlier <a data-recto-link="1" href="https://example.com/other">link</a></p>',
      'whatever',
      'anchor',
      'https://example.com/target'
    );
    expect(out.alreadyLinked).toBe(true);
  });
});

describe('pushLink — failure-code classification', () => {
  beforeEach(() => {
    vi.useFakeTimers();
    vi.setSystemTime(new Date('2026-05-29T11:00:00Z'));
  });
  afterEach(() => {
    vi.useRealTimers();
    vi.restoreAllMocks();
  });

  async function withFetch(stub: (url: string, init?: RequestInit) => Response | Promise<Response>) {
    vi.stubGlobal('fetch', vi.fn(async (url: string, init?: RequestInit) => stub(url, init)) as any);
    return makeEncrypted('VFcye71lskZfg524pevNyYSd');
  }

  it('wp_auth_failed on 401', async () => {
    const secret = await withFetch(() => new Response('Unauthorized', { status: 401 }));
    const r = await pushLink({ RECTO_KEK: KEK }, baseInput({ encryptedSecret: secret }));
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.code).toBe('wp_auth_failed');
  });

  it('wp_security_blocked on 403 (Wordfence-shaped)', async () => {
    const secret = await withFetch(() => new Response('<html>Generated by Wordfence</html>', { status: 403 }));
    const r = await pushLink({ RECTO_KEK: KEK }, baseInput({ encryptedSecret: secret }));
    if (r.ok) throw new Error('should have failed');
    expect(r.code).toBe('wp_security_blocked');
  });

  it('wp_post_not_found on 404', async () => {
    const secret = await withFetch(() => new Response('Not Found', { status: 404 }));
    const r = await pushLink({ RECTO_KEK: KEK }, baseInput({ encryptedSecret: secret }));
    if (r.ok) throw new Error('should have failed');
    expect(r.code).toBe('wp_post_not_found');
  });

  it('wp_rest_disabled on 406 (some hardening plugins)', async () => {
    const secret = await withFetch(() => new Response('Not Acceptable', { status: 406 }));
    const r = await pushLink({ RECTO_KEK: KEK }, baseInput({ encryptedSecret: secret }));
    if (r.ok) throw new Error('should have failed');
    expect(r.code).toBe('wp_rest_disabled');
  });

  it('wp_network when fetch throws', async () => {
    vi.stubGlobal('fetch', vi.fn(async () => { throw new TypeError('refused'); }) as any);
    const secret = await makeEncrypted('VFcye71lskZfg524pevNyYSd');
    const r = await pushLink({ RECTO_KEK: KEK }, baseInput({ encryptedSecret: secret }));
    if (r.ok) throw new Error('should have failed');
    expect(r.code).toBe('wp_network');
  });

  it('wp_already_linked when a previous recto anchor is present', async () => {
    const existing = '<p>body <a data-recto-link="1" href="https://example.com/other">x</a></p>';
    const secret = await withFetch((u, init) => {
      if ((init?.method ?? 'GET') === 'GET') {
        return new Response(JSON.stringify({ id: 42, content: { raw: existing } }), {
          status: 200,
          headers: { 'content-type': 'application/json' },
        });
      }
      return new Response('', { status: 200 });
    });
    const r = await pushLink({ RECTO_KEK: KEK }, baseInput({ encryptedSecret: secret }));
    if (r.ok) throw new Error('should have failed');
    expect(r.code).toBe('wp_already_linked');
  });

  it('happy path → ok with revisionId', async () => {
    const existing = '<p>first paragraph here.</p>\n\n<p>second paragraph.</p>';
    let calls = 0;
    const secret = await withFetch((u, init) => {
      calls += 1;
      if (calls === 1) {
        return new Response(JSON.stringify({ id: 42, content: { raw: existing } }), {
          status: 200,
          headers: { 'content-type': 'application/json' },
        });
      }
      return new Response(JSON.stringify({ id: 42, modified: '2026-05-29T11:00:01' }), {
        status: 200,
        headers: { 'content-type': 'application/json' },
      });
    });
    const r = await pushLink({ RECTO_KEK: KEK }, baseInput({ encryptedSecret: secret, paragraphMarker: 'first paragraph here.' }));
    expect(r.ok).toBe(true);
    if (r.ok) expect(r.postId).toBe(42);
  });
});
